<?
$SYS_FUNCTIONS_A = array(
   "sys/parameters.php" => array("ID" => "00900","NAME" => "Parameters","DESCRIPTION" => "Parameters","LANG_ID" => "VA_BI_P","IMAGE" => "","OPEN_WIN" => "0"),
   "dictionary/main.php" => array("ID" => "00901","NAME" => "Dictionary","DESCRIPTION" => "Data Dictionary","LANG_ID" => "VA_BI_DD","IMAGE" => "","OPEN_WIN" => "0"),
   "region/regionbrowser.php" => array("ID" => "00910","NAME" => "Region","DESCRIPTION" => "Region Management","LANG_ID" => "VA_BI_REGION","IMAGE" => "","OPEN_WIN" => "0"),
   "sys/utility/reginfo.php" => array("ID" => "011011","NAME" => "Register Information","DESCRIPTION" => "Register Information","LANG_ID" => "VA_SI_OG_R","IMAGE" => "","OPEN_WIN" => "0"),
   "sys/utility/depart.php" => array("ID" => "011012","NAME" => "Department","DESCRIPTION" => "Department Management","LANG_ID" => "VA_SI_OG_D","IMAGE" => "","OPEN_WIN" => "0"),
   "sys/utility/role.php" => array("ID" => "011014","NAME" => "Roles&Permissions","DESCRIPTION" => "Roles&Permissions","LANG_ID" => "VA_SI_OG_P","IMAGE" => "","OPEN_WIN" => "0"),
   "sys/utility/user.php" => array("ID" => "011013","NAME" => "Users","DESCRIPTION" => "Users Management","LANG_ID" => "VA_SI_OG_U","IMAGE" => "","OPEN_WIN" => "0"),
   "sys/interface.php" => array("ID" => "0110401","NAME" => "Screen","DESCRIPTION" => "Screen Setting","LANG_ID" => "VA_SI_IS_S","IMAGE" => "","OPEN_WIN" => "0"),
   "language/main.php" => array("ID" => "0110404","NAME" => "Language Define","DESCRIPTION" => "Language Define","LANG_ID" => "VA_SI_IS_LANGDEFINE","IMAGE" => "","OPEN_WIN" => "0"),
   "language/package.php" => array("ID" => "0110405","NAME" => "Language Package","DESCRIPTION" => "Language Package","LANG_ID" => "VA_SI_IS_LANGPACKAGE","IMAGE" => "","OPEN_WIN" => "0"),
   "language/import.php" => array("ID" => "0110406","NAME" => "Import Language File","DESCRIPTION" => "Import Language File","LANG_ID" => "VA_SI_IS_LANGIMPORT","IMAGE" => "","OPEN_WIN" => "0"),
   "sys/sysevent.php" => array("ID" => "01118","NAME" => "系统日志管理","DESCRIPTION" => "","LANG_ID" => "VA_SI_SL","IMAGE" => "","OPEN_WIN" => "0"),
   "sys/register.php" => array("ID" => "01120","NAME" => "系统信息","DESCRIPTION" => "","LANG_ID" => "VA_SI_SI","IMAGE" => "","OPEN_WIN" => "0"),
   "task/taskbrowser.php" => array("ID" => "01121","NAME" => "System Tasks","DESCRIPTION" => "System Tasks Management","LANG_ID" => "VA_SI_TM","IMAGE" => "","OPEN_WIN" => "0"),
   "controlpanel/person_info.php" => array("ID" => "01122","NAME" => "控制面板","DESCRIPTION" => "","LANG_ID" => "VA_SI_CP","IMAGE" => "","OPEN_WIN" => "0"),
   "branch/brancheditor.php" => array("ID" => "10001","NAME" => "Add Branch","DESCRIPTION" => "Add a branch to system","LANG_ID" => "VB_BM_AB","IMAGE" => "","OPEN_WIN" => "0"),
   "branch/branchbrowser.php" => array("ID" => "10002","NAME" => "Branch Browser","DESCRIPTION" => "Browse all of the branch","LANG_ID" => "VB_BM_BB","IMAGE" => "","OPEN_WIN" => "0"),
   "branch/clientbrowser.php" => array("ID" => "10004","NAME" => "Branch Terminals","DESCRIPTION" => "Branch Terminals Management","LANG_ID" => "VB_BM_BT","IMAGE" => "","OPEN_WIN" => "0"),
   "branch/cancellation.php" => array("ID" => "10009","NAME" => "Cancellation","DESCRIPTION" => "Cancel a branch","LANG_ID" => "VB_BM_CA","IMAGE" => "","OPEN_WIN" => "0"),
   "generalsms/newsms.php" => array("ID" => "14001","NAME" => "New SMS","DESCRIPTION" => "Send New SMS","LANG_ID" => "VB_GS_NSMS","IMAGE" => "","OPEN_WIN" => "0"),
   "generalsms/receivedbrowser.php" => array("ID" => "14002","NAME" => "Received SMS","DESCRIPTION" => "View the Received SMS","LANG_ID" => "VB_GS_REC","IMAGE" => "","OPEN_WIN" => "0"),
   "generalsms/sentbrowser.php" => array("ID" => "14003","NAME" => "SMS Sent","DESCRIPTION" => "View the SMS Sent","LANG_ID" => "VB_GS_SENT","IMAGE" => "","OPEN_WIN" => "0"),
   "sms/receivedbrowser.php" => array("ID" => "15001","NAME" => "Received SMS","DESCRIPTION" => "View the Received SMS","LANG_ID" => "VB_SMS_REC","IMAGE" => "","OPEN_WIN" => "0"),
   "sms/processedbrowser.php" => array("ID" => "15002","NAME" => "Processed SMS","DESCRIPTION" => "View the Processed SMS","LANG_ID" => "VB_SMS_PRO","IMAGE" => "","OPEN_WIN" => "0"),
   "sms/sendingbrowser.php" => array("ID" => "15003","NAME" => "SMS Sending","DESCRIPTION" => "View the SMS Sending","LANG_ID" => "VB_SMS_SEND","IMAGE" => "","OPEN_WIN" => "0"),
   "sms/sentbrowser.php" => array("ID" => "15004","NAME" => "SMS Sent","DESCRIPTION" => "View the SMS Sent","LANG_ID" => "VB_SMS_SENT","IMAGE" => "","OPEN_WIN" => "0"),
   "sms/vendbrowser.php" => array("ID" => "15005","NAME" => "SMS Vending","DESCRIPTION" => "View the SMS Vending","LANG_ID" => "VB_SMS_VEND","IMAGE" => "","OPEN_WIN" => "0"),
   "mail/accountbrowser.php" => array("ID" => "16001","NAME" => "Mail Account","DESCRIPTION" => "Mail Account","LANG_ID" => "VB_MAIL_ACCOUNT","IMAGE" => "","OPEN_WIN" => "0"),
   "mail/templatebrowser.php" => array("ID" => "16002","NAME" => "Mail Template","DESCRIPTION" => "Mail Template","LANG_ID" => "VB_MAIL_TEMPLATE","IMAGE" => "","OPEN_WIN" => "0"),
   "mail/emailview.php" => array("ID" => "16003","NAME" => "Mail View","DESCRIPTION" => "Mail View","LANG_ID" => "VB_MAIL_VIEW","IMAGE" => "","OPEN_WIN" => "0")
);
?>